### PR TITLE
added blog and github project from mahou5x

### PR DESCRIPTION
**Pull request by mfarache**
Added extra entries 
CQRS with micronaut
Serverless function 
Deploying micronaut 
And one github project

### CODE REVIEW

**Review by JonasTebben — CHANGES_REQUESTED** [review]
Hey Mauricio! Thanks for submitting your changes 👍 That's great. Would you like to change the last link on your username to point to your profile instead of pointing to the project itself twice?

**Review by mfarachepiksel — COMMENTED** [review]
done

**Comment by mfarachepiksel** [comment]
sorry i did not use the same github user in the second commit, but it's me :)

**Comment by JonasTebben** [comment]
@all-contributors please add @mfarache for doc

**Pull request merged**
